Repository JP-s-Children/FineApple, pull requests merged in 2023-05, with the labels that each got.

#2 [REFAC] 구조 변경
  client/firebase/app.js
  client/src/App.jsx
  client/src/components/RootError.jsx
  client/src/components/auth/SignInForm.jsx
  client/src/components/auth/SignUpForm.jsx
  client/src/components/common/nav/ComputerItSubMenu.jsx
  client/src/components/common/nav/GameSubMenu.jsx
  client/src/components/common/nav/MenuList.jsx
  client/src/components/common/nav/Nav.jsx
  client/src/components/common/nav/UserMenu.jsx
  client/src/components/community/CommunityCategorySection.jsx
  client/src/components/community/ComputerItHeader.jsx
  client/src/components/community/DeletePostModal.jsx
  client/src/components/community/GameHeader.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/autoComplete/AutoComplete.jsx
  client/src/components/community/autoComplete/AutoCompleteItem.jsx
  client/src/components/community/autoComplete/NothingFound.jsx
  client/src/components/community/comment/Comment.jsx
  client/src/components/community/posts/EmptyPostIndicator.jsx
  client/src/components/community/posts/PostItem.jsx
  client/src/components/community/posts/PostSection.jsx
  client/src/components/community/question/QuestionForm.jsx
  client/src/components/community/rank/RankItem.jsx
  client/src/components/profile/Profile.jsx
  client/src/components/profile/ProfileEditForm.jsx
  client/src/components/profile/RegisterProductButton.jsx
  client/src/constants/routes.js
  client/src/pages/Home.jsx
  client/src/pages/RegisterProduct.jsx
  client/src/pages/SignIn.jsx
  client/src/services/auth.js
  client/src/services/comments.js
  client/src/services/config.js
  client/src/services/firebase.js
  client/src/services/posts.js
  client/src/services/utils.js
Labels: REFACTOR

#3 [FIX] 변경 파일 구조 import문 수정
  client/src/components/community/DeletePostModal.jsx
  client/src/components/community/question/QuestionForm.jsx
  client/src/pages/PreparePage.jsx
  client/src/queries/postDetailQuery.js
  client/src/queries/postsByCategoryQuery.js
Labels: FIX, REFACTOR

#5 [FEAT] CategorySelect 구현 및 Home 페이지 컴포넌트 재구성
  client/src/components/common/InfoCard.jsx
  client/src/components/community/TextEditor.jsx
  client/src/components/community/autoComplete/AutoComplete.jsx
  client/src/components/community/autoComplete/AutoCompleteItem.jsx
  client/src/components/community/comment/Comment.jsx
  client/src/components/community/home/CategorySelect.jsx
  client/src/components/community/home/ContentInfoModal.jsx
  client/src/components/community/home/QuestionInfoModal.jsx
  client/src/components/community/home/RuleInfoModal.jsx
  client/src/components/community/home/Tutorials.jsx
  client/src/components/community/home/index.js
  client/src/components/community/index.js
  client/src/constants/category.js
  client/src/constants/categoryList.js
  client/src/constants/transientOptions.js
  client/src/hooks/queries/useAutoCompleteQuery.js
  client/src/pages/Home.jsx
  client/src/services/posts.js
  client/src/services/utils.js
Labels: FEAT, REFACTOR, STYLE

#9 [FEAT] AuthenticationGuard 수정
  client/src/App.jsx
  client/src/guard/AuthenticationGuard.jsx
  client/src/loaders/index.js
  client/src/loaders/myPostsLoader.js
  client/src/loaders/myProfileLoader.js
  client/src/queries/myProfileQuery.js
  client/src/services/auth.js
Labels: FEAT

#11 [FIX] AuthenticationGuard 수정
  client/src/components/common/nav/Nav.jsx
  client/src/guard/AuthenticationGuard.jsx
Labels: FIX

#12 [FEAT] PopularPosts 컴포넌트 및 관련 firebase query 구현
  client/src/App.jsx
  client/src/components/common/Footer.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/Logo.jsx
  client/src/components/common/nav/MenuList.jsx
  client/src/components/common/nav/ThemeButton.jsx
  client/src/components/community/CategoryPosts.jsx
  client/src/components/community/Faq.jsx
  client/src/components/community/PopularPosts.jsx
  client/src/components/community/autoComplete/AutoComplete.jsx
  client/src/components/community/home/CategorySelect.jsx
  client/src/components/community/index.js
  client/src/components/community/posts/EmptyPostIndicator.jsx
  client/src/components/community/posts/PostSection.jsx
  client/src/hooks/queries/useAutoCompleteQuery.js
  client/src/hooks/useInfinityScroll.js
  client/src/pages/CategoryPosts.jsx
  client/src/pages/GuideFaq.jsx
  client/src/pages/PopularPosts.jsx
  client/src/pages/index.js
  client/src/queries/index.js
  client/src/queries/popularPostsByCategoryQuery.js
  client/src/services/posts.js
  client/src/styles/GlobalStyle.js
Labels: FIX, FEAT, STYLE

#13 [STYLE] css 전역 변수 일부 색상 palette 변경으로 컴포넌트 스타일 수정
  client/index.html
  client/public/favicon.ico
  client/public/logo-dark.svg
  client/public/logo-light.svg
  client/src/components/auth/SignInForm.jsx
  client/src/components/common/Footer.jsx
  client/src/components/common/Logo.jsx
  client/src/components/common/form/InputWrapper.jsx
  client/src/components/common/nav/Nav.jsx
  client/src/components/community/CategoryPosts.jsx
  client/src/components/community/PopularPosts.jsx
  client/src/components/community/autoComplete/AutoComplete.jsx
  client/src/components/community/autoComplete/AutoCompleteItem.jsx
  client/src/components/community/comment/CommentSection.jsx
  client/src/components/community/home/CategorySelect.jsx
  client/src/components/community/home/Tutorials.jsx
  client/src/components/community/posts/EmptyPostIndicator.jsx
  client/src/components/community/posts/PostSection.jsx
  client/src/components/community/posts/SideMenu.jsx
  client/src/pages/Home.jsx
  client/src/pages/SignIn.jsx
  client/src/queries/popularPostsByCategoryQuery.js
  client/src/queries/postsByCategoryQuery.js
  client/src/services/posts.js
  client/src/styles/GlobalStyle.js
Labels: FIX, STYLE

#14 계정 관련 페이지 구조 변경
  client/src/App.jsx
  client/src/components/common/AvatarIcon.jsx
  client/src/components/common/nav/ComputerItSubMenu.jsx
  client/src/components/common/nav/GameSubMenu.jsx
  client/src/components/common/nav/Nav.jsx
  client/src/components/common/nav/SubMenu.jsx
  client/src/components/common/nav/ThemeButton.jsx
  client/src/components/common/nav/UserMenu.jsx
  client/src/components/community/question/SelectProductRadio.jsx
  client/src/components/profile/MyProfile.jsx
  client/src/components/profile/Profile.jsx
  client/src/components/profile/ProfileHeader.jsx
  client/src/components/profile/RegisterProductButton.jsx
  client/src/components/profile/index.js
  client/src/constants/routes.js
  client/src/pages/MyFavPosts.jsx
  client/src/pages/MyProfile.jsx
  client/src/pages/ProfileLayout.jsx
  client/src/pages/index.js
  client/src/queries/myProfileQuery.js
  client/src/services/profile.js
Labels: FEAT, STYLE

#22 [REFAC] Faq 관련 UI 및 Home 페이지 Modal 내용 수정
  client/src/components/common/PopupModal.jsx
  client/src/components/community/Faq.jsx
  client/src/components/community/autoComplete/NothingFound.jsx
  client/src/components/community/comment/LikeChip.jsx
  client/src/components/community/home/ContentInfoModal.jsx
  client/src/components/community/home/HighlightText.jsx
  client/src/components/community/home/QuestionInfoModal.jsx
  client/src/components/community/home/RuleInfoModal.jsx
  client/src/components/community/home/index.js
  client/src/components/community/posts/PostSection.jsx
  client/src/loaders/postsByCategoryLoader.js
  client/src/pages/GuideFaq.jsx
  client/src/pages/Home.jsx
Labels: FEAT, REFACTOR, STYLE

#23 [REFAC] CategoryList -> CATEGORY_INFO로 상수 변경
  client/src/pages/Home.jsx
Labels: REFACTOR

#24 [FEAT] ProfileEdit
  client/src/components/profile/MyProductList.jsx
  client/src/components/profile/MyProfile.jsx
  client/src/components/profile/ProfileEditForm.jsx
  client/src/components/profile/SelectInterestCategories.jsx
  client/src/components/profile/index.js
  client/src/services/auth.js
  client/src/services/profile.js
Labels: FEAT

#26 [REFAC] 사용안하는 파일 제거
  client/src/components/common/index.js
  client/src/components/common/selectProduct/SelectProduct.jsx
  client/src/components/common/selectProduct/SelectProductAccordion.jsx
  client/src/components/common/selectProduct/SelectProductAccordionPanel.jsx
  client/src/components/common/selectProduct/SelectedProduct.jsx
  client/src/components/common/selectProduct/index.js
  client/src/components/community/question/CategoryRadio.jsx
  client/src/components/community/question/MyProductListPanel.jsx
  client/src/components/community/question/SelectProductRadio.jsx
  client/src/components/community/question/SelectedCategoryAndProductType.jsx
  client/src/components/community/question/SubjectSelect.jsx
  client/src/components/community/question/index.js
  client/src/constants/categoryList.js
  client/src/constants/productList.js
  client/src/constants/productThumbnail.js
Labels: REFACTOR

#28 [FIX] 에러 메시지 중복 및 회원가입 이슈 해결
  client/src/components/auth/SignInForm.jsx
  client/src/components/auth/SignUpForm.jsx
  client/src/components/common/form/DuplicateCheckInput.jsx
  client/src/components/common/form/index.js
  client/src/components/profile/ProfileEditForm.jsx
  client/src/services/auth.js
Labels: FIX, FEAT, REFACTOR

#29 [FEAT] Profile 컴포넌트 - 사용자 프로필 정보
  client/package.json
  client/src/components/community/question/SelectCategory.jsx
  client/src/components/community/rank/RankTable.jsx
  client/src/components/profile/AvatarProfileInfo.jsx
  client/src/components/profile/InterestCategories.jsx
  client/src/components/profile/MyProfile.jsx
  client/src/components/profile/index.js
  client/src/pages/Profile.jsx
  client/src/queries/profileByNickNameQuery.js
  client/src/services/auth.js
  client/src/services/profile.js
  client/src/utils/countryCode.js
Labels: FIX, FEAT, STYLE

#30 [FEAT] point
  client/src/components/community/DeletePostModal.jsx
  client/src/components/community/question/SelectCategory.jsx
  client/src/services/point.js
  client/src/services/posts.js
Labels: FEAT

#31 [REFAC] getSearchedPosts 코드 리팩토링 및 내가 작성한 질문 관련 query 함수 수정
  client/public/community/filter-content-modal.png
  client/public/community/ipad/ipad-category.png
  client/public/community/ipad/ipad-family.png
  client/public/community/iphone/iphone-category.png
  client/public/community/iphone/iphone-family.png
  client/public/community/mac/mac-category.png
  client/public/community/mac/mbp-notebooks.png
  client/src/components/common/nav/SubMenu.jsx
  client/src/components/common/nav/ThemeButton.jsx
  client/src/components/community/CategoryPosts.jsx
  client/src/components/community/ComputerItHeader.jsx
  client/src/components/community/PopularPosts.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/posts/PostSection.jsx
  client/src/hooks/mutations/index.js
  client/src/pages/Home.jsx
  client/src/pages/MyPosts.jsx
  client/src/pages/Post.jsx
  client/src/queries/myPostsQuery.js
  client/src/queries/popularPostsByCategoryQuery.js
  client/src/services/posts.js
  client/src/services/utils.js
Labels: FIX, FEAT, REFACTOR, STYLE

#32 [FEAT] MyPosts 페이지 컴포넌트 Suspense 구현 및 스타일 수정
  client/src/components/community/DeletePostModal.jsx
  client/src/components/community/comment/LikeChip.jsx
  client/src/pages/MyPosts.jsx
  client/src/queries/myPostsQuery.js
  client/src/styles/GlobalStyle.js
Labels: FEAT, STYLE

#33 [FEAT] 내가 좋아요 누른 글 목록 페이지, query 구현
  client/src/components/common/InfoCard.jsx
  client/src/components/common/PopupModal.jsx
  client/src/components/common/nav/ProfileSubMenu.jsx
  client/src/components/community/home/QuestionInfoModal.jsx
  client/src/components/community/posts/PostItem.jsx
  client/src/components/profile/MyProfile.jsx
  client/src/pages/MyFavPosts.jsx
  client/src/pages/MyPosts.jsx
  client/src/queries/index.js
  client/src/queries/myLikePostsQuery.js
  client/src/services/posts.js
Labels: FIX, FEAT, STYLE

#34 [FEAT] 사용자 프로필
  client/src/components/common/Header.jsx
  client/src/components/common/nav/Nav.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/profile/AvatarProfileInfo.jsx
  client/src/components/profile/AvatarProfileInfoDetail.jsx
  client/src/components/profile/AvatarProfileInfoLink.jsx
  client/src/components/profile/ProfileInfo.jsx
  client/src/components/profile/index.js
  client/src/pages/Profile.jsx
  client/src/queries/index.js
  client/src/queries/profileByEmailQuery.js
  client/src/services/profile.js
Labels: FEAT, STYLE

#35 [FEAT] Rank - infinite query로 변경 및 loader 제거
  client/src/App.jsx
  client/src/components/common/nav/UserMenu.jsx
  client/src/components/community/rank/RankTable.jsx
  client/src/hooks/queries/useRankUsersQuery.js
  client/src/loaders/index.js
  client/src/loaders/rankLoader.js
  client/src/pages/Rank.jsx
  client/src/pages/RegisterProduct.jsx
  client/src/pages/index.js
  client/src/queries/index.js
  client/src/queries/rankQuery.js
  client/src/services/profile.js
Labels: FEAT, STYLE

#36 [FIX] createComment 요청 시 level 데이터 누락 수정 및 createAt 프로퍼티 데이터 undefined 버그 수정
  client/src/components/auth/SignInForm.jsx
  client/src/components/auth/SignUpForm.jsx
  client/src/components/common/Header.jsx
  client/src/components/common/Toast.jsx
  client/src/components/common/nav/ComputerItSubMenu.jsx
  client/src/components/common/nav/MenuList.jsx
  client/src/components/common/nav/Nav.jsx
  client/src/components/common/nav/ThemeButton.jsx
  client/src/components/common/nav/UserMenu.jsx
  client/src/components/community/DeletePostModal.jsx
  client/src/components/community/PostContent.jsx
  client/src/components/community/ShowMoreButton.jsx
  client/src/components/community/autoComplete/AutoCompleteItem.jsx
  client/src/components/community/comment/CommentSection.jsx
  client/src/components/community/posts/EmptyPostIndicator.jsx
  client/src/components/community/posts/PostItem.jsx
  client/src/components/community/posts/PostSection.jsx
  client/src/components/community/question/QuestionForm.jsx
  client/src/components/profile/ProfileEditForm.jsx
  client/src/constants/mutateComment.js
  client/src/hooks/useToast.js
  client/src/pages/GuideFaq.jsx
  client/src/pages/Home.jsx
  client/src/pages/Profile.jsx
  client/src/pages/Question.jsx
  client/src/pages/SignIn.jsx
  client/src/queries/myProfileQuery.js
  client/src/queries/popularPostsByCategoryQuery.js
  client/src/queries/postsByCategoryQuery.js
  client/src/queries/postsByNickNameQuery.js
  client/src/queries/profileByEmailQuery.js
  client/src/queries/profileByNickNameQuery.js
  client/src/services/comments.js
  client/src/services/profile.js
  server/mock-data/posts.js
  server/router/auth.js
  server/router/post.js
Labels: FIX, FEAT, REFACTOR, STYLE
